### ISSUE TITLE
Please publish to npm

### ISSUE THREAD

**Issue by NickHeiner** [marklagendijk/ui-router.stateHelper#4]
[npm](https://www.npmjs.org/) is a popular package manager for js. If you publish this module there, it will allow it to be consumed via [browserify](browserify.org). All you need to do is add a `name` and `version` to `package.json` and run `npm publish` in this repo.

**Comment by jgoux** [comment]
I'd love to see this package on NPM. As Angular is published on NPM too, I'd prefer to keep a single package manager instead of installing bower just for one lib.
So a big +1 for it. :)

**Comment by kburson** [comment]
+1.  Working with angular all my dependencies come thru npm.  I used to use bower, but we had so many problems with it that we eventually only used it for setting up our project,then  we committed all the packages to our project repository so they would be available for every build rather than using bower to download them on every build.  (The build used to break randomly when bower had a panic attack).

I any case, the angular team has migrated to using npm over bower; angular-ui-router is available on npm now, so it makes sense to have the ui-router.stateHelper available on npm as well to keep all dependencies together.

Currently I am forced to use bower to download stateHelper, which then downloads copies of angular and angular-ui-router from bower.  so now I have 2 copies of the angular dependencies, one in bower_components and one in node_modules... not very efficient.

Please update the package.json and run npm publish...  thank you.
